export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_EXIST_SERVICE = 'EDIT_EXIST_SERVICE';
export const  SAVE_SERVICE = 'SAVE_SERVICE';
export const CANCEL = 'CANCEL';
export const FILTER_SERVICE = 'FILTER_SERVICE';